//! The strict pending check (plan 23a and 23l; lead, 2026-10-09). A pending id must fail on the testkit: an id that passes
//! leaves `conformance/core-pending.txt`. Two kinds of pending id are exempt:
//!
//! - **real-only**: the pinned replacement map gives the id a `slow:*` proof. The testkit cannot prove it, so the strict
//!   run does not run it. `conformance/core-real-only.txt` is derived from the map (`cargo xtask ledger-ids --write`), never
//!   written by hand.
//! - **held**: `conformance/core-held.txt` lists a pending id that passes but stays pending, with its reason class, owner and
//!   authority. A held id must pass: a held id that fails is an error, so the list cannot go stale. A `budget` id is over the
//!   time budget, so the strict run runs it at the first seed of the set only (lead, 2026-10-09): its full-seed proof is
//!   missing, and the held file says so.
//!
//! Formats (fields separated by two or more spaces, as in `status`):
//!
//! ```text
//! conf::<id>  slow:<what>                                          (core-real-only.txt)
//! conf::<id>  budget|unproven  owner: <package>  (<authority>)  because: <why>   (core-held.txt)
//! ```

use crate::status::{clause, lines};
use std::collections::BTreeSet;

/// The environment variable that turns the conformance harness into the strict pending run. `cargo xtask ci` sets it in
/// its `lists` step.
pub const STRICT_ENV: &str = "BOTSTER_PENDING_STRICT";

/// A Core id whose proof in the pinned replacement map is `slow:*`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RealOnly {
    pub id: String,
    pub proof: String,
}

/// The reason class of a held id. `real-only` is not a class of the held file: those ids come from the replacement map.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeldReason {
    /// The id passes, but over the default-tier time budget. It runs at the first seed only.
    Budget,
    /// The id passes on the testkit, but that pass does not prove the clause; the line names the missing proofs. It runs at
    /// every seed, and its line leaves the file in the PR that adds the last missing proof (lead, 2026-10-09).
    Unproven,
}

/// A pending id that passes on the testkit and stays pending.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Held {
    pub id: String,
    pub reason: HeldReason,
    pub owner: String,
    pub authority: String,
    pub because: String,
}

/// The real-only Core ids of a replacement map (`conformance/replacement-map.json` of botster-contracts), sorted by id.
pub fn real_only_of_map(
    map_json: &str,
    core_ids: &BTreeSet<String>,
) -> Result<Vec<RealOnly>, String> {
    let json: serde_json::Value =
        serde_json::from_str(map_json).map_err(|e| format!("the replacement map: {e}"))?;
    let rows = json["ids"]
        .as_array()
        .ok_or("the replacement map has no `ids`")?;
    let mut real_only = Vec::new();
    for row in rows {
        let (Some(id), Some(proof)) = (row["id"].as_str(), row["proof"].as_str()) else {
            return Err(format!(
                "a replacement map row has no `id` or `proof`: {row}"
            ));
        };
        if core_ids.contains(id) && proof.starts_with("slow:") {
            real_only.push(RealOnly {
                id: id.to_string(),
                proof: proof.to_string(),
            });
        }
    }
    real_only.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(real_only)
}

/// The text of `core-real-only.txt`.
pub fn real_only_text(real_only: &[RealOnly]) -> String {
    let mut text = String::from(
        "# Generated by `cargo xtask ledger-ids --write` from the pinned replacement map: the Core ids with a `slow:*` proof.\n",
    );
    for entry in real_only {
        text.push_str(&format!("{}  {}\n", entry.id, entry.proof));
    }
    text
}

/// Parses `core-real-only.txt`.
pub fn parse_real_only(text: &str) -> Result<Vec<RealOnly>, String> {
    lines(text)
        .map(|(line, fields)| match fields[..] {
            [id, proof] if id.starts_with("conf::") && proof.starts_with("slow:") => Ok(RealOnly {
                id: id.to_string(),
                proof: proof.to_string(),
            }),
            _ => Err(format!("line {line}: expected `conf::<id>  slow:<what>`")),
        })
        .collect()
}

/// Parses `core-held.txt`.
pub fn parse_held(text: &str) -> Result<Vec<Held>, String> {
    lines(text)
        .map(|(line, fields)| {
            let [id, reason, owner, authority, because] = fields[..] else {
                return Err(format!("line {line}: expected five fields"));
            };
            if !id.starts_with("conf::") {
                return Err(format!("line {line}: `{id}` is not an id"));
            }
            let reason = match reason {
                "budget" => HeldReason::Budget,
                "unproven" => HeldReason::Unproven,
                other => {
                    return Err(format!(
                        "line {line}: the reason class `{other}` is not `budget` or `unproven` (a real-only id comes from the replacement map)"
                    ))
                }
            };
            let owner = owner
                .strip_prefix("owner: ")
                .ok_or_else(|| format!("line {line}: `owner: <package>` is missing"))?;
            let authority = clause(authority)
                .ok_or_else(|| format!("line {line}: the authority in parentheses is missing"))?;
            let because = because
                .strip_prefix("because: ")
                .ok_or_else(|| format!("line {line}: `because:` is missing"))?;
            Ok(Held {
                id: id.to_string(),
                reason,
                owner: owner.trim().to_string(),
                authority: authority.to_string(),
                because: because.trim().to_string(),
            })
        })
        .collect()
}

/// The problems of the held file against the pending file and the real-only ids. Empty means the file is valid.
pub fn held_problems(
    held: &[Held],
    pending: &BTreeSet<String>,
    real_only: &[RealOnly],
) -> Vec<String> {
    let mut problems = Vec::new();
    let mut seen = BTreeSet::new();
    for entry in held {
        if !seen.insert(&entry.id) {
            problems.push(format!("core-held.txt: {} is listed twice", entry.id));
        }
        if !pending.contains(&entry.id) {
            problems.push(format!(
                "core-held.txt: {} is not pending; a held id is a pending id",
                entry.id
            ));
        }
        if real_only.iter().any(|r| r.id == entry.id) {
            problems.push(format!(
                "core-held.txt: {} is real-only in the replacement map; it needs no held entry",
                entry.id
            ));
        }
    }
    problems
}

/// What the strict run does with a pending id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Class {
    /// Not run: the testkit cannot prove it.
    RealOnly(RealOnly),
    /// Runs, and must pass.
    Held(Held),
    /// Runs, and must fail.
    Pending,
}

/// The class of a pending id. A real-only id is real-only even when the held file names it (`held_problems` reports that).
pub fn class_of(id: &str, real_only: &[RealOnly], held: &[Held]) -> Class {
    if let Some(entry) = real_only.iter().find(|r| r.id == id) {
        Class::RealOnly(entry.clone())
    } else if let Some(entry) = held.iter().find(|h| h.id == id) {
        Class::Held(entry.clone())
    } else {
        Class::Pending
    }
}

/// The seeds at which the strict run runs a pending id of `class`: a `budget` held id at the first seed only, every other id
/// at every seed of the set.
pub fn seeds_of(class: &Class, seeds: &[u64]) -> Vec<u64> {
    match class {
        Class::Held(Held {
            reason: HeldReason::Budget,
            ..
        }) => seeds.iter().take(1).copied().collect(),
        _ => seeds.to_vec(),
    }
}

/// The strict result of a pending id that ran on the testkit: `Ok(note)` when its result is the expected one, else the error.
pub fn verdict(id: &str, class: &Class, passed: bool) -> Result<String, String> {
    match (class, passed) {
        (Class::Pending, false) => Ok("pending: fails as expected".to_string()),
        (Class::Pending, true) => Err(format!(
            "{id} is pending and passes on the testkit: remove it from conformance/core-pending.txt"
        )),
        (Class::Held(entry), true) => Ok(format!(
            "held ({:?}, owner {}): passes and stays pending",
            entry.reason, entry.owner
        )),
        (Class::Held(_), false) => Err(format!(
            "{id} is held but failing: remove its line from conformance/core-held.txt (it stays pending), or fix it"
        )),
        (Class::RealOnly(entry), _) => Ok(format!("real-only ({}): not run", entry.proof)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HELD: &str = "# a comment\n\
        conf::slow_query  budget  owner: p4b-queries-files (unstaffed)  (lead, 2026-10-09)  because: 2.005 s, over 2 s\n";

    fn ids(list: &[&str]) -> BTreeSet<String> {
        list.iter().map(|s| s.to_string()).collect()
    }

    fn real(id: &str) -> RealOnly {
        RealOnly {
            id: id.into(),
            proof: "slow:lock".into(),
        }
    }

    /// Only a Core id with a `slow:*` proof is real-only: another proof, or an id of another contract, is not.
    #[test]
    fn the_real_only_ids_are_the_core_ids_with_a_slow_proof() {
        let map = r#"{"version": 1, "ids": [
            {"id": "conf::z_lock", "proof": "slow:lock", "note": "x"},
            {"id": "conf::a_lock", "proof": "slow:dir"},
            {"id": "conf::kit", "proof": "core-testkit"},
            {"id": "conf::real", "proof": "real:pty"},
            {"id": "conf::hub_lock", "proof": "slow:lock"}
        ]}"#;
        let core = ids(&["conf::z_lock", "conf::a_lock", "conf::kit", "conf::real"]);
        let real_only = real_only_of_map(map, &core).unwrap();
        let found: Vec<&str> = real_only.iter().map(|r| r.id.as_str()).collect();
        assert_eq!(found, ["conf::a_lock", "conf::z_lock"]);
        assert_eq!(
            parse_real_only(&real_only_text(&real_only)).unwrap(),
            real_only
        );
        assert!(real_only_of_map("{}", &core).is_err());
        assert!(real_only_of_map(r#"{"ids": [{"id": "conf::a"}]}"#, &core).is_err());
        assert!(parse_real_only("conf::a  core-testkit\n").is_err());
        assert!(parse_real_only("a  slow:x\n").is_err());
    }

    #[test]
    fn a_held_line_gives_its_class_owner_authority_and_reason() {
        assert_eq!(
            parse_held(HELD).unwrap(),
            [Held {
                id: "conf::slow_query".into(),
                reason: HeldReason::Budget,
                owner: "p4b-queries-files (unstaffed)".into(),
                authority: "lead, 2026-10-09".into(),
                because: "2.005 s, over 2 s".into(),
            }]
        );
        let bad = |line: &str| parse_held(line).unwrap_err();
        assert!(bad("conf::a  real-only  owner: p  (x)  because: y\n")
            .contains("not `budget` or `unproven`"));
        let unproven =
            parse_held("conf::a  unproven  owner: p6-testkit  (x)  because: y\n").unwrap();
        assert_eq!(unproven[0].reason, HeldReason::Unproven);
        assert!(bad("conf::a  budget  p  (x)  because: y\n").contains("owner"));
        assert!(bad("conf::a  budget  owner: p  x  because: y\n").contains("authority"));
        assert!(bad("conf::a  budget  owner: p  (x)  y\n").contains("because"));
        assert!(bad("a  budget  owner: p  (x)  because: y\n").contains("not an id"));
        assert!(bad("conf::a  budget  owner: p  (x)\n").contains("five fields"));
    }

    /// A held id is pending, once, and not real-only.
    #[test]
    fn a_held_id_is_a_pending_id_once_and_not_real_only() {
        let held = parse_held(HELD).unwrap();
        assert!(held_problems(&held, &ids(&["conf::slow_query"]), &[]).is_empty());
        let problems = held_problems(&held, &ids(&[]), &[]);
        assert_eq!(problems.len(), 1);
        assert!(problems[0].contains("not pending"), "{problems:?}");
        let problems = held_problems(
            &held,
            &ids(&["conf::slow_query"]),
            &[real("conf::slow_query")],
        );
        assert_eq!(problems.len(), 1);
        assert!(problems[0].contains("real-only"), "{problems:?}");
        let twice = [held.clone(), held].concat();
        let problems = held_problems(&twice, &ids(&["conf::slow_query"]), &[]);
        assert_eq!(problems.len(), 1);
        assert!(problems[0].contains("twice"), "{problems:?}");
    }

    /// Both sides are strict: a pending id that passes is an error, and a held id that fails is an error.
    #[test]
    fn a_pending_id_must_fail_and_a_held_id_must_pass() {
        let held = parse_held(HELD).unwrap();
        let real_only = [real("conf::lock")];
        assert_eq!(class_of("conf::other", &real_only, &held), Class::Pending);
        let as_real = class_of("conf::lock", &real_only, &held);
        assert_eq!(as_real, Class::RealOnly(real_only[0].clone()));
        let as_held = class_of("conf::slow_query", &real_only, &held);
        assert_eq!(as_held, Class::Held(held[0].clone()));

        assert!(verdict("conf::other", &Class::Pending, false).is_ok());
        let error = verdict("conf::other", &Class::Pending, true).unwrap_err();
        assert!(
            error.contains("remove it from conformance/core-pending.txt"),
            "{error}"
        );
        assert!(verdict("conf::slow_query", &as_held, true).is_ok());
        let error = verdict("conf::slow_query", &as_held, false).unwrap_err();
        assert!(error.contains("held but failing"), "{error}");
        assert!(verdict("conf::lock", &as_real, true).is_ok());
        assert!(verdict("conf::lock", &as_real, false).is_ok());

        // A real-only id stays real-only when the held file also names it.
        let both = [real("conf::slow_query")];
        assert_eq!(
            class_of("conf::slow_query", &both, &held),
            Class::RealOnly(both[0].clone())
        );
    }

    /// A `budget` held id runs at the first seed of the set only; an `unproven` or pending id runs at every seed.
    #[test]
    fn a_budget_id_runs_at_the_first_seed_and_a_pending_id_at_every_seed() {
        let held = parse_held(HELD).unwrap();
        let class = class_of("conf::slow_query", &[], &held);
        assert_eq!(seeds_of(&class, &[3, 4, 5]), [3]);
        assert_eq!(seeds_of(&class, &[]), Vec::<u64>::new());
        assert_eq!(seeds_of(&Class::Pending, &[3, 4, 5]), [3, 4, 5]);
        let unproven = parse_held("conf::b  unproven  owner: p  (x)  because: y\n").unwrap();
        assert_eq!(
            seeds_of(&Class::Held(unproven[0].clone()), &[3, 4, 5]),
            [3, 4, 5]
        );
        assert_eq!(
            seeds_of(&Class::RealOnly(real("conf::lock")), &[3, 4]),
            [3, 4]
        );
    }

    /// The checked-in files parse, and agree: the held ids are pending and not real-only.
    #[test]
    fn the_checked_in_files_parse_and_agree() {
        let real_only =
            parse_real_only(include_str!("../../../conformance/core-real-only.txt")).unwrap();
        let held = parse_held(include_str!("../../../conformance/core-held.txt")).unwrap();
        let pending: BTreeSet<String> = include_str!("../../../conformance/core-pending.txt")
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("conf::"))
            .map(str::to_string)
            .collect();
        assert!(real_only
            .iter()
            .any(|r| r.id == "conf::lc_2_data_dir_is_exclusive"));
        assert!(held_problems(&held, &pending, &real_only).is_empty());
    }
}
