[package]
name = "botster-core-link"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
botster-core-contract.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
bolero.workspace = true
