//! Source generation for the `#[test]`-per-id pattern (design 6.1). Uses `std` only, so a `build.rs` can include this file.
//!
//! A runner crate's `build.rs` lists its transcript ids and writes `render_test_macro(..)` to `$OUT_DIR`. The crate includes that file.
//! The generated `macro_rules!` takes the subject factory and, optionally, the schema resolver of the suite. It expands to one `#[test]` per id.

/// The test function name of an id: `conf::en_8_x` becomes `conf_en_8_x`.
pub fn test_name(id: &str) -> String {
    id.replace("::", "_")
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Renders a `#[macro_export] macro_rules! <macro_name>` that takes `$make:expr` and expands to one `#[test]` per id.
///
/// `dir_expr` is a Rust expression for the `&include_dir::Dir` that holds the transcripts. `crate_name` is the runner crate, for the reproduce command.
pub fn render_test_macro(
    macro_name: &str,
    crate_name: &str,
    dir_expr: &str,
    ids: &[String],
) -> String {
    let mut sorted: Vec<&String> = ids.iter().collect();
    sorted.sort();
    let mut out = String::new();
    out.push_str("// Generated by the runner build script. Do not edit.\n");
    out.push_str(&format!(
        "#[macro_export]\nmacro_rules! {macro_name} {{\n    ($make:expr) => {{\n        {macro_name}!($make, ::botster_conformance::NoSchemas);\n    }};\n    ($make:expr, $schemas:expr) => {{\n"
    ));
    for id in sorted {
        out.push_str(&format!(
            "        #[test]\n        fn {}() {{\n            ::botster_conformance::run_one_test({:?}, {}, {:?}, &$make, &$schemas);\n        }}\n",
            test_name(id),
            crate_name,
            dir_expr,
            id
        ));
    }
    out.push_str("    };\n}\n");
    out
}
