[package]
name = "botster-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
botster-core-contract.workspace = true

[dev-dependencies]
botster-conformance.workspace = true
botster-core-conformance.workspace = true
libtest-mimic.workspace = true
static_assertions.workspace = true
toml.workspace = true

[[test]]
name = "conformance"
path = "../../tests/conformance.rs"
harness = false
